name: Gatling CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'gradle'
      - name: Build with Gradle
        run: ./gradlew build --no-daemon
  gatling-test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'gradle'
      - name: Run Gatling Tests
        env:
          TWITTER_API_TOKEN: ${{ secrets.TWITTER_API_TOKEN }}
        run: ./gradlew gatlingRun-cl.gera.apitwitter2.simulations.ManageTweetsSimulation --no-daemon