name: Gatling CI

on: [ push ]

jobs:
  gatling-test:
    runs-on: ubuntu-latest
    env:
      TW_CLIENT_ID: ${{ secrets.TW_CLIENT_ID }}
      TW_CLIENT_SECRET: ${{ secrets.TW_CLIENT_SECRET }}
      TW_ACCESS_TOKEN: ${{ secrets.TW_ACCESS_TOKEN }}
      TW_REFRESH_TOKEN: ${{ secrets.TW_REFRESH_TOKEN }}
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
      GH_REPOSITORY: ${{ github.repository }}
      GH_REPOSITORY_PUBLIC_KEY: ${{ secrets.GH_REPOSITORY_PUBLIC_KEY }}
      GH_REPOSITORY_KEY_ID: ${{ secrets.GH_REPOSITORY_KEY_ID }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Twitter authentication
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: runAuthApp > authApp.out
        run: | 
          echo "TW_ACCESS_TOKEN=$(grep 'TwitterTokens' authApp.out  | perl -lpe 's/^TwitterTokens\((.*),(.*)\)/$1/')" >> $GITHUB_ENV
          echo "TW_REFRESH_TOKEN=$(grep 'TwitterTokens' authApp.out  | perl -lpe 's/^TwitterTokens\((.*),(.*)\)/$2/')" >> $GITHUB_ENV
      - name: Run Gatling Tests
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: gatlingRun-cl.gera.apitwitter2.simulations.ManageTweetsSimulation