name: Gatling CI

on:
  push:
    branches:
      - main
      - github-actions
  workflow_dispatch:

jobs:
  gatling-test:
    runs-on: ubuntu-latest
    env:
      TW_CLIENT_ID: ${{ secrets.TW_CLIENT_ID }}
      TW_CLIENT_SECRET: ${{ secrets.TW_CLIENT_SECRET }}
      TW_ACCESS_TOKEN: ${{ secrets.TW_ACCESS_TOKEN }}
      TW_REFRESH_TOKEN: ${{ secrets.TW_REFRESH_TOKEN }}
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
      GH_REPOSITORY: ${{ github.repository }}
      GH_REPOSITORY_PUBLIC_KEY: ${{ secrets.GH_REPOSITORY_PUBLIC_KEY }}
      GH_REPOSITORY_KEY_ID: ${{ secrets.GH_REPOSITORY_KEY_ID }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
      - name: Twitter authentication
        run: ./gradlew runAuthApp
      - name: Update Twitter env vars
        run: |
          echo "TW_ACCESS_TOKEN=$(cat tw_access_token)" >> $GITHUB_ENV
          echo "TW_REFRESH_TOKEN=$(cat tw_refresh_token)" >> $GITHUB_ENV
      - name: Run Gatling Tests
        run: ./gradlew gatlingRun-cl.gera.apitwitter2.simulations.BasicSimulation
      - name: Upload report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: gatling-report
          path: ./build/reports
      - name: Generate Summary
        uses: actions/github-script@v6
        with:
          script: |
            const createSummary = require('./.github/scripts/gatling-summary-actions.js')
            createSummary(core, './build/reports/gatling')
  deploy:
    needs: gatling-test
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: gatling-report
          path: report
      - name: Add content to branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          keep_files: true
          publish_branch: gh-pages
          publish_dir: report
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: gh-pages
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: .
          name: github-pages
          retention-days: 1
      - name: Deploy artifact
        uses: actions/deploy-pages@v1
        with:
          emit_telemetry: false
          timeout: 600000
          error_count: 10
          reporting_interval: 5000
          artifact_name: github-pages
          preview: false
          
        
