name: Deploy

on:
#  push:
#    branches:
#      - main
#      - github-actions
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Preparing
        run: |
          mkdir public
          cd public
          echo "<h1>Hola Mundo</h1>" > hola.html
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: gera-cl/gera-cl.github.io
          publish_branch: main
          publish_dir: ./public